/** "Today's First Read" — the narrative morning note under The Read: the
 * editorial expansion of the one-line tldr. Generated by the VeniceAI API when
 * a key is set, otherwise a deterministic composer. Renders nothing when the
 * brief carries no note, so a keyless/older artifact degrades cleanly. */
import type { DailyBrief } from "../lib/contracts";

export function FirstRead({ brief }: { brief: DailyBrief }) {
  const text = brief.first_read?.trim();
  if (!text) return null;
  return (
    <section aria-label="Today's First Read" className="border-b border-hairline bg-card">
      <div className="mx-auto max-w-[1400px] px-4 py-4 sm:px-6">
        <div className="flex items-baseline justify-between gap-3">
          <h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-muted">
            Today's First Read
          </h2>
          <span className="num text-[10px] text-faint">{brief.first_read_engine}</span>
        </div>
        <p className="mt-1.5 max-w-[72ch] text-[14px] leading-relaxed text-ink sm:text-[15px]">
          {text}
        </p>
      </div>
    </section>
  );
}
